version: "3.9"

services:
  jupyter:
    build: .
    ports:
      - "8888:8888"               # Expose container port 8888 to host
    volumes:
      - ./:/home/jovyan/work       # Mount repo to container
    working_dir: /home/jovyan/work
    container_name: dsci522_jupyter
    environment:
      JUPYTER_ENABLE_LAB: "yes"
    command: start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''
