services:
  dockerlock:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - ./:/work
    working_dir: /work
    container_name: dsci522_jupyter
    environment:
      PASSWORD: dsci522
    command: start-notebook.py
